server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # RUTA DE USUARIOS (La que ya tenías y funciona)
        - id: ruta-usuarios
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuarios/**

        # RUTA DE PEDIDOS (La nueva entrada)
        - id: ruta-pedidos
          uri: http://localhost:8082
          predicates:
            - Path=/api/pedidos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway