server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-usuarios
          uri: lb://MS-USUARIOS
          predicates:
            - Path=/api/usuarios/**

        - id: ms-pedidos
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/api/pedidos/**

        - id: ms-inventario
          uri: lb://MS-INVENTARIO
          predicates:
            - Path=/api/inventario/**

        - id: ms-menu
          uri: lb://MS-MENU
          predicates:
            - Path=/api/menu/**

        - id: ms-detalle-pedido
          uri: lb://MS-DETALLE-PEDIDO
          predicates:
            - Path=/api/detalle-pedido/**

        - id: ms-reservas
          uri: lb://MS-RESERVAS
          predicates:
            - Path=/api/reservas/**

        - id: ms-cocina
          uri: lb://MS-COCINA
          predicates:
            - Path=/api/cocina/**

        - id: ms-pagos
          uri: lb://MS-PAGOS
          predicates:
            - Path=/api/pagos/**

        - id: ms-notificaciones
          uri: lb://MS-NOTIFICACIONES
          predicates:
            - Path=/api/notificaciones/**

        - id: ms-mesas
          uri: lb://MS-MESAS
          predicates:
            - Path=/api/mesas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/