server:
  port: 8092

spring:
  application:
    name: ms-mesas
  datasource:
    url: jdbc:mysql://db-mysql:3306/db_mesas
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true