server:
  port: 8086

spring:
  application:
    name: ms-detalle-pedido
  datasource:
    url: jdbc:mysql://localhost:3306/db_detalle_pedido
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/db_detalle_pedido

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/